persistence: "POSTGRESQLDETTES"

repository:
  clientRepository: com.asn.data.repositories.jpa.ClientRepositoryImplJpa
  articleRepository: com.asn.data.repositories.jpa.ArticleRepositoryImplJpa
  commandeRepository: com.asn.data.repositories.jpa.CommandeRepositoryImplJpa
  detailRepository: com.asn.data.repositories.jpa.DetailRepositoryImplJpa
